/*
 * request.cgi.designer.cs --
 *
 * Copyright (c) 2007-2012 by Joe Mistachkin.  All rights reserved.
 *
 * See the file "license.terms" for information on usage and redistribution of
 * this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * RCS: @(#) $Id: $
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8964
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapok.certificate
{
    /// <summary>
    /// This class is the tool-generated designer partial for the certificate
    /// request CGI page; it contains no members and exists to be combined with
    /// the corresponding hand-written partial class.
    /// </summary>
    public partial class request
    {
        // nothing.
    }
}
