/*
 * provision.cgi.designer.cs --
 *
 * Copyright (c) 2007-2012 by Joe Mistachkin.  All rights reserved.
 *
 * See the file "license.terms" for information on usage and redistribution of
 * this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * RCS: @(#) $Id: $
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8964
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapok.service
{
    /// <summary>
    /// This class is the tool-generated portion of the Kapok provisioning CGI
    /// page.  It is combined with the hand-written code-behind for the same
    /// page to form the complete page implementation.
    /// </summary>
    public partial class provision
    {
        // nothing.
    }
}
